name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6' ]
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
    - name: bundler
      run: gem install bundler:1.17.3
    - name: setup
      run: bundle
    - name: compile
      run: make compile_db
    - name: make test
      run: make test
